### ISSUE TITLE
Decide between setting nonces in the contract or resetting nonces in the sidechain

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/loomchain#1136]
Migrating to the Distributed-Gateway can be problematic if a user has a non-zero nonce in their account's receipt.

The bug can be conceptually understood in the following scenario:
User has made a withdrawal on current gateway. Their contractNonce is now 1, and their account nonce for their receipts is also 1.

Distributed-Gateway gets deployed. Their nonce is 0, but their account nonce in the sidechain is still 1. 

Result: Invalid signatures, disallowing the user from withdrawing.

Ways to resolve:
1. Initialize all user nonces on the mainnet contract with their nonce amount from the sidechain in the gateway's constructor
2. Reset all the users' nonces on the sidechain. This means that users are potentially able to replay the signature that was associated with their 0'th nonce withdrawal. I doubt any user actually kept all signatures around, and this is only dangerous if we reset the nonces before we actually migrate the funds to the distributed gateway. 

I'm in favor of 2, really don't want to mess with the contracts' code further.

**Comment by enlight** [comment]
Closing in favor of https://github.com/loomnetwork/transfer-gateway/issues/59
