### ISSUE TITLE
eth_sendRawTransaction modified to handle Ethereum transactions 

### ISSUE THREAD

**Issue by Sriep** [loomnetwork/loomchain#1177]
`eth_sendRawTransaction`, expects the input to be a TM tx, which isn't very useful because Web3 compatible clients don't send TM txs. We want that endpoint to accept Eth txs from any Web3 compatible client.

**Comment by Sriep** [comment]
Fixed by https://github.com/loomnetwork/loomchain/pull/1227 and https://github.com/loomnetwork/go-loom/pull/391

**Comment by enlight** [comment]
Resolved
