### ISSUE TITLE
Upgrade to a newer build of EVM

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/loomchain#1181]
We are one major hard fork behind on EVM, we should upgrade this. Ideally we would upgrade the evm, but then have a feature flag that enables the hard fork on the EVM interpreter so it can be done inplace

**Comment by enlight** [comment]
Feature flag to enable Constantinople hard fork in the EVM was added in https://github.com/loomnetwork/loomchain/pull/1345

Will also upgrade go-ethereum to the latest stable release in the near future (https://github.com/loomnetwork/loomchain/pull/1374)
