### ISSUE TITLE
BNB Oracle implementation

### ISSUE THREAD

**Issue by tstxni97** [loomnetwork/loomchain#1187]
- Oracle needs an ability to listen to the specific account on BNB chain looking for `transfer` event. It is possible to use https://github.com/binance-chain/go-sdk to accomplish the task
- Oracle needs an ability to tell loom gateway to mint Loom coin on our dappchain
- Oracle needs an ability to tell loom gateway to transfer token on BNB chain to a specific account once dappchain gateway receive BNB coin.

- Also see `Hot Wallet` which implement polling from a specific mainnet address

**Comment by phoorichet** [comment]
Binance TG Oracle is now on in a separated repo.
