### ISSUE TITLE
Implementation of Binance signer on loomchain

### ISSUE THREAD

**Issue by tstxni97** [loomnetwork/loomchain#1198]
- we need Binance signer as a test helper for Binance gateway unit test
- we also need a Binance `recover` function for address mapping
- we also need to find a way to do account mapping bnb <=> default
- keys are like bitcoin's. secp256k1. Private key is 32 bytes and public key is 33 bytes
- sign using ECDSA on curve secp256k1. should very similar to what we have

**Comment by phoorichet** [comment]
Apparently we don't need Binance signer because there is still no official wallet, like Metamask, that we can integrate with at this moment.
