### ISSUE TITLE
Add on-chain build number tracking

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1208]
We need a better way of checking which build validators are running on PlasmaChain, we could extend the ChainConfig contract to store the build number for each validator, and have the validator nodes self-report their build number on startup similar to how they auto-enable feature flags.

Also need a CLI command that can print out which build each validator is on, and a percentage of validators on each build.

**Comment by atchapcyp** [comment]
Here is the list of method we need to implement on `ChainConfig` contract.
- `SetBuildNumber` <- To let validator set their current build version before start-up node
- `GetBuildNumber` <- To inquire build number
- `ListBuildNumber`  <-To get all build number from validators

method SetBuildNumber must only be use in `ChainConfig` version 1.2

Also, change `ChainConfig` routine to automatically update their own build number

About the CLI command :
- `loom chain-cfg list-build-numbers `
For printing out build number of each validator, and percentage

**Comment by enlight** [comment]
`ListBuildNumber` -> `ListBuildNumbers`
Looks good otherwise.

**Comment by enlight** [comment]
Resolved in https://github.com/loomnetwork/loomchain/pull/1265
