### ISSUE TITLE
Kick offline validators out of the validator set

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1246]
If a validator hasn't signed a block in the last 4 periods (where a period consists of N consecutive blocks) then:

1. All delegations to the offline validator should be redelegated to the limbo validator, thus allowing the delegators to redelegate their delegations to another validator (though they can also withdraw them entirely at that point).
2. The offline validator should be removed from the whitelist so that they stop earning rewards on the funds deposited in the time lock contract.
3. Since the offline validator should have no whitelisted amount, nor any delegations they should be removed from the validator set on the next election (this shouldn't require any new code in theory?).

**Comment by aupiff** [comment]
(3.) should not require any new code, no.

If a validator has been down for this long, once slashing is enabled their delegations will have already been slashed several times prior to them being down for 4 consecutive periods of N blocks--just something to keep in mind. The plan is still to add slashing directly after this feature is added?

**Comment by aupiff** [comment]
#1250 fixes this
