### ISSUE TITLE
Multi-node deployment failed

### ISSUE THREAD

**Issue by LyonNee** [loomnetwork/loomchain#1249]
I am following the documentation here.[link](https://loomx.io/developers/en/multi-node-deployment.html)

`oasis@Oasis:~$ sudo systemctl status loom.service
● loom.service - Loom
   Loaded: loaded (/etc/systemd/system/loom.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-06-20 00:51:47 CST; 2s ago
  Process: 13615 ExecStart=/home/oasis/loom-chain/loom run --persistent-peers tcp://99af5db97dcaedad381de36c6cb99a6532638013@192.168.1.66:46656,tcp://ccd953c512eb7b096cb6d6055eb18ef9592e1f85@192.16
 Main PID: 13615 (code=exited, status=1/FAILURE)

Jun 20 00:51:47 Oasis systemd[1]: Started Loom.
Jun 20 00:51:47 Oasis loom[13615]: Error: invalid character -- Amino:JSON int/int64/uint/uint64 expects quoted values for javascript numeric support, got: 10.
Jun 20 00:51:47 Oasis systemd[1]: loom.service: Main process exited, code=exited, status=1/FAILURE
Jun 20 00:51:47 Oasis systemd[1]: loom.service: Unit entered failed state.
Jun 20 00:51:47 Oasis systemd[1]: loom.service: Failed with result 'exit-code'.
`

**Comment by mattkanwisher** [comment]
Yikes that multinode doc is out of date. We will get it updated. In mean time did you try just getting a single node working? I would start there. Also the example is using DPoS version 1 we are on version 3, you can safely remove that from the genesis.json

**Comment by mattkanwisher** [comment]
Also that error implies a config is using an integer instead of string, odd. Did you modify the config.toml? A fresh single node is best place to start

**Comment by LyonNee** [comment]
@mattkanwisher 

I did not modify the config.toml file.I have tried a single node deployment and it has been successful.So I want to try multi-node deployment now. When is the documentation updated?

**Comment by mattkanwisher** [comment]
Updated https://github.com/loomnetwork/loom-sdk-documentation/pull/250 

Hard refresh the page 
https://loomx.io/developers/en/multi-node-deployment.html 

the biggest change should be 
```
Power: "10"
```
also it should be DPosV3 by default

**Comment by LyonNee** [comment]
What parameters should be filled in the “local” in the genesis.json #1 file? 
Can the “chainId” be filled in casually?

**Comment by LyonNee** [comment]
What parameters should be filled in the “address” in the genesis.json #2 file?
