### ISSUE TITLE
JSON RPC eth_call issue

### ISSUE THREAD

**Issue by eduardonunesp** [loomnetwork/loomchain#1259]
The `JSON RPC` interface for call [eth_call](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_call) method needs a fix, for instance calling a method `balanceOf` on a contract `ERC721`.

Calling `ERC721` contract method `balanceOf`

```bash
curl -X POST --data '{"id":0,"jsonrpc":"2.0","method":"eth_call","params":[{"to": "0x473a5fd078a2f5ba1b74e507e3a6e2a2cc55396f", "data": "0x70a08231000000000000000000000000473a5fd078a2f5ba1b74e507e3a6e2a2cc55396f"}]}' http://localhost:46658/eth
```

Gives the following error: 

```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "error": {
    "code": -32000,
    "message": "Server error",
    "data": "loom error: failed to resolve account address: unknown chain ID "
  }
}
```

> The call above is the same used by `blockscout` which uses only the fields `to` and `data`, because `from` is optional parameter

The `eth_call` still works using the LoomProvider legacy methods

**Comment by Sriep** [comment]
eth_call currently only supports EVM transactions. Is ERC721 a go-transaction?
We need to add some code to find out whether its an EVM or go-transactions by unmarshalling the query-data.

**Comment by Sriep** [comment]
Also, the problem might be the lack of a from address. `curl -X POST --data '{"id":0,"jsonrpc":"2.0","method":"eth_call","params":[{"to": "0x3d7Fc003CD15B4c42C9300708673eA22b386AA2A", "data": "0x6d4ce63c", "from":"0x7E402be3d3A83FF850dc22775d33E89fFD374dD1"}]}' http://localhost:46658/eth` seems to work.

**Comment by eduardonunesp** [comment]
This case is an `ERC721` call for `EVM`. Yep, it will work. Now we need to add a way to make the `from` an optional value as the `JSON RPC` specification describes

**Comment by eduardonunesp** [comment]
Fixed
