### ISSUE TITLE
JSON RPC should expose the Ethereum stored on account by calling `eth_getBalance` on address

### ISSUE THREAD

**Issue by eduardonunesp** [loomnetwork/loomchain#1268]
The `JSON RPC` call for `eth_getBalance` isn't exposing the value correctly for a given address, although it works on the previous protobuf interface it didn't work for `JSON RPC` new interface needing return the Ethereum for a given account.

For instance, the call below doesn't return the correct value

```bash
>> {"id": 0, "jsonrpc":"2.0", "method": "eth_getBalance", "params": ["0x53c22427e7D0061A6A83F4fc3184b25033b9b0FB"]}
<< {
  "result": "0x0",
  "jsonrpc": "2.0",
  "id": 0
}
``` 

And the address above has some value stored on plasmachain, as we can see on command `loom gateway account`

```bash
$ loom gateway account default:0x53c22427e7D0061A6A83F4fc3184b25033b9b0FB -u http://plasma.dappchains.com:80
{
  "DAppChainAddress": "0x53c22427e7D0061A6A83F4fc3184b25033b9b0FB",
  "EthereumAddress": "0x86D4859bE772b5c3445A9AA7e82ad930369309f7",
  "LOOM": "0 (0)",
  "ETH": "0 (15184681712962962)"
}```

**Comment by Sriep** [comment]
Implemented in https://github.com/loomnetwork/loomchain/pull/1269
