### ISSUE TITLE
Allow swapping deployer keys in UserWhitelistContract

### ISSUE THREAD

**Issue by mukuls9971** [loomnetwork/loomchain#1284]
Need to be able to swap out one deployer key for another, so devs can rotate keys if they need to.

**Comment by mukuls9971** [comment]
I assume we are replacing one deployerAddr(old) by other(new), so tier corresponding to these contracts can change
1. We need to append the old deployer contracts to new deployer, but keep the old deployer state with empty list of contracts as it is in user-deployer-whitelist
2. ContractToTierMap will be refreshed after the interval automatically, no need to change anything there.
3. ContractToBlockTxn will be reset after blockRange. 
So any such change will be applicable after ContractDataRefreshInterval and oldTier.BlockRange blocks, 
@ParthDesai Please suggest any changes in above understanding

**Comment by mukuls9971** [comment]
Further Details of function SwapUserDeployer() in userDeployerWhitelist contract
  -SwapUserDeployerRequest includes OldDeployerAddr and NewDeployerAddr
  -transfer fees by calling coin contract method TransferFrom
  -Add NewDeployerAddr and remove OldDeployerAddr by calling deployer_whitelist contract
  -Update userstate in userDeployerWhitelist contract by modifying list of deployers
  -Update deployerState in userDeployerWhitelist contract by adding new state corresponding to NewDeployerAddr and modifying older one corresponding to OldDeployerAddr

@enlight @ParthDesai plz comment on this understanding  when you have time .. please have a look on first comment too ..

**Comment by enlight** [comment]
Shouldn't need to transfer any fees, the fee has already been paid by the user when they added the old deployer account.
