### ISSUE TITLE
Remove CachingStore

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1300]
The `CachingStore` in `store/cachingstore.go` has been superseded by the `versionedCachingStore`, we should try to eliminate it from the code base provided that gamechain clusters don't rely on it.

**Comment by pathornteng** [comment]
Just checked the code, it seems that we should not get rid of CachingStore until we migrate gamechain to AppStorev3 and deprecate AppStorev1

**Comment by enlight** [comment]
@pathornteng does gamechain even use EVM contracts?

**Comment by pathornteng** [comment]
No, should we migrate it to AppStorev3?

**Comment by enlight** [comment]
Yes, we should.

**Comment by pathornteng** [comment]
All of Gamechain clusters have been migrated to AppStore v3. We can remove CachingStore now.

**Comment by sidharth747** [comment]
@suhasagg please reference the PR for this issue.

**Comment by suhasagg** [comment]
PR for the caching store removal - https://github.com/loomnetwork/loomchain/pull/1384

**Comment by enlight** [comment]
Resolved by https://github.com/loomnetwork/loomchain/pull/1384
