### ISSUE TITLE
Add an address format option flag to addressmapper commands 

### ISSUE THREAD

**Issue by pathornteng** [loomnetwork/loomchain#1304]
We should add an option flag `--hex` to these addressmapper commands 
```
loom addressmapper get-mapping 
loom addressmapper list-mappings 
```
So that they return mapping addresses in hexadecimal.

**Comment by enlight** [comment]
Hex should be the default, I don't think we need a `--base64` flag even, just output hex.
Also `list-mappings` should be displayed in a table similar to how the contract mapping are displayed by this command:
```
loom gateway list-contract-mappings -u http://test-z-us1.dappchains.com:80
```
