### ISSUE TITLE
Validator Tools not process gateway configs

### ISSUE THREAD

**Issue by phoorichet** [loomnetwork/loomchain#1314]
Makeing `validator-tools` without `gateway` tag will skip all the gateway template. When running the command `validator-tools new`,  there is no `gateway` configurations created even thought the gateway configurations are given.

https://github.com/loomnetwork/loomchain/blob/2a1ed72fda185c8f672438dd163b8090e9e3a019/config/config.go#L776
https://github.com/loomnetwork/loomchain/blob/2a1ed72fda185c8f672438dd163b8090e9e3a019/config/gateway_config.go#L35

**Comment by enlight** [comment]
Yep, need to make sure that `validators-tool` is built with the `gateway` tag when you plan to use it with the `gateway` build variant.

**Comment by phoorichet** [comment]
transfer-gateway-v2 e2e is using this `validators-tool` build. I guess we can add this tag to Makefile to make sure it's getting the correct configurations.

**Comment by phoorichet** [comment]
#1318

**Comment by enlight** [comment]
Should be resolved now.
