### ISSUE TITLE
Extend e2e test harness to support running clusters with a mix of builds

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1325]
We need to be able to run the e2e tests with nodes that are on different builds, this should help us detect consensus breaking changes between production release builds. It should work something like this:

1. Given build numbers X & Y, where X < Y.
2. In each multi-node e2e test spin up 1 node on build Y, and the rest on build X.

Might need a better way to detect consensus failure, right now I don't think it's obvious one has occurred during a test, gotta dig through logs.

These multi-build e2e tests will be run in a separate Jenkins job where build numbers X & Y will be parameters. The job will run once a day and will set Y to match the last successful build, and X to match the current production build.

**Comment by Sriep** [comment]
Added new environmental variables to jenkins.sh
```bash
export LOOMEXE_PATH="../loom"
export LOOMEXE_ALTPATH="../loom2"
export MIN_VALIDATORS=2
export MIN_ALT_VALIDATORS=2
export ALWAYS_APPHASH_CHECK="yes"
make test
```
LOOMEXE_PATH and LOOMEXE_ALTPATH are paths to too loom builds you want to test.
MIN_VALIDATORS and MIN_ALT_VALIDATORS how many nodes you want using each of the two builds. Will override the settings already set.
ALWAYS_APPHASH_CHECK if non-empty will do a `chckeapphash` at the end of every test.

**Comment by enlight** [comment]
Resolved by https://github.com/loomnetwork/loomchain/pull/1333
