### ISSUE TITLE
Binance Transfer Gateway should allow devs to map their own contracts

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1326]
Similar to the Ethereum & TRON Transfer Gateways third-party devs should be able to deploy a contract to the DAppChain and map it to a token on Binance Chain.

**Comment by phoorichet** [comment]
Binance Gatway needs to have a signer function so third-party can do a contract mapping by themselve using both DAppChain and Binance Keys. I previously had a PR that added this signer. Let's me recreate it again.

**Comment by enlight** [comment]
Resolved.
