### ISSUE TITLE
Make lazy EVM root saving in multi-writer store more reliable

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1335]
The gist is that we only save the versioned root hash to evm.db when it changes, so it's possible to end with an error like this after restarting the node:

```
Error: EVM roots mismatch, evm.db(32): 250E14A528FE0D4665DC309903B451D2614BFDE56B72C27814238F40D8A70A92, app.db(35): DF11774E9B0E71565D6A94F6B7228A7F18AC117F4C6A8842FF116F799DD7629E
```

We can't just ignore the error as implemented in
https://github.com/loomnetwork/loomchain/pull/1313

We probably need to check versions first, and hashes second, and do something sensible depending on what doesn't match.

**Comment by pathornteng** [comment]
So the above error can happen when we use old evm.db. This can only happen during AppStore v1 to AppStore v3 migration which has been done. Currently, AppStore v3 is the default, and AppStore v1 is soon to be deprecated. So this is not going to be an issue anymore.

**Comment by enlight** [comment]
OK, going to close this now. Let us know if run into this again @Sriep
