### ISSUE TITLE
JSON RPC eth_getTransactionReceipt improvement

### ISSUE THREAD

**Issue by eduardonunesp** [loomnetwork/loomchain#1347]
The command [eth_getTransactionReceipt](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt) when called with a specific hash that doesn't exist, should return `null` on the result instead of an error, it should return errors only when really there's an error.

Current behavior 

```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "error": {
    "code": -32000,
    "message": "Server error",
    "data": "loom error: Tx (D93C44702F5BDBDF9652FE82F6E94B7684EEA4227161F9C11F5139786C19ED1A) not found"
  }
}
```

The expected result of not found the receipt
```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": null
}
```

**Comment by enlight** [comment]
Resolved by https://github.com/loomnetwork/loomchain/pull/1349
