### ISSUE TITLE
Review nonce handling strategy

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1360]
Failed evm txs can be included in blocks, but they cannot alter chain state in any way, only successful txs can change chain state. The per-account tx nonce is stored in chain state so it doesn't get incremented when an EVM tx fails. We should investigate the possibility of incrementing nonces for failed txs to better emulate Ethereum,

**Comment by pathornteng** [comment]
Saving nonce in chain state makes us unable to update nonce when transactions revert. One possible solution is to move all account nonces to receipts_db so it does not change app hash when we update nonce.

**Comment by enlight** [comment]
OK, then we should probably increment the nonce if a tx fails in DeliverTx, but we need to be super careful that only the nonce is updated, and all other state changes are discarded.

**Comment by enlight** [comment]
We can modify `NonceHandler` so it can be given a `KVStore` (reference to `Application.Store`) when the nonce middleware are constructed. That way the `NonceHandler` can increment the nonce unconditionally in `DeliverTx` directly via the `KVStore`.

**Comment by pathornteng** [comment]
Expected NonceMiddleware Behavior

1. If a tx has been included in `BlockStore`, account nonce should increment. This means EVM reverted tx will increment account nonce.
2. An account can submit multiple txs in one blocks
3. Should nonce client speculate nonce or always query from the server? A tx with speculative nonce can get `Invallid nonce` if the previous tx does not pass `CheckTx`

Example
Block 1
Successful Tx -> nonce = 1
EVM reverted Tx -> nonce = 2
Successful Tx -> nonce = 3

Block 2
Successful Tx -> nonce = 4
Error Tx (Tx does not pass CheckTx) -> nonce  = 4 
Successful Tx -> nonce = 5

**Comment by enlight** [comment]
Should be resolved by https://github.com/loomnetwork/loomchain/pull/1410
