### ISSUE TITLE
Negative value showing in transaction details

### ISSUE THREAD

**Issue by Sriep** [loomnetwork/loomchain#1361]
`eth_getBlockByHash` is displaying negative amounts in transaction `value` fields. the value field should always be non-negative.

**Comment by Sriep** [comment]
This could be that the transaction as originally posted had a negative value or the value filed was manipulated incorrectly at some point.

**Comment by Sriep** [comment]
Addressed in https://github.com/loomnetwork/loomchain/pull/1350

**Comment by enlight** [comment]
Resolved
