### ISSUE TITLE
Websocket abruptly closed on eth_unsubscribe

### ISSUE THREAD

**Issue by eduardonunesp** [loomnetwork/loomchain#1366]
Websocket connection is been abruptly closed when `eth_unsubscribe` is called, the expected behavior is to only cancel a subscription for a particular subscription not to close the WebSocket connection.

In order to test you can use the [wscat](https://www.npmjs.com/package/wscat2)

```bash
$ wscat ws://localhost:46658/eth
```

It will create stdin to WebSocket, enter the line
```json
{"id": 1, "method": "eth_subscribe", "params": ["logs", {"address": "0x8320fe7702b96808f7bbc0d4a888ed1468216cfd", "topics": ["0xd78a0cb8bb633d06981248b816e7bd33c2a35a6089241d099fa519e361cab902"]}]}
```

The result should be something like
```json
{
  "result": "0xae867c2d60a45eafe3c9fd0264ccef59",
  "jsonrpc": "2.0",
  "id": 1
}
```

Then send the unsubscribe using the result from the previous command, like:

```json
{"id": 1, "method": "eth_unsubscribe", "params": ["0xae867c2d60a45eafe3c9fd0264ccef59"]}
``` 

You'll notice that the connection will be closed ending the `wscat` command, the expected behavior is to stay connected to the WebSocket after unsubscribe from a previous subscription.

**Comment by Sriep** [comment]
WebSocket was explicitly closed when closing subscription. Removed this in https://github.com/loomnetwork/loomchain/pull/1369 .
