### ISSUE TITLE
add-identity-mapping cmd doesn't set correct sig type for TRON

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1378]
When signing with a TRON key the sig type should be set to `SignatureType_TRON`
https://github.com/loomnetwork/loomchain/blob/3134c2fff8613a60305bd0392eb45c8f19f1701b/cmd/loom/addressmapper.go#L63

And `builtin/plugins/address_mapper/address_mapper_test.go` should be updated to run every test using all sig types.

**Comment by phoorichet** [comment]
This PR https://github.com/loomnetwork/loomchain/pull/1385 fix the issue.

**Comment by enlight** [comment]
Resolved
