### ISSUE TITLE
Fix receipt not found error

### ISSUE THREAD

**Issue by pathornteng** [loomnetwork/loomchain#1396]
Currently, receipt not found error still persists in a few function calls. Our junior team is having a problem with EVM event scanner due to receipt not found error like

```
  August 6th 2019, 04:57:02.710    templeraid-scan    error: failed to get logs for TempleTimeUpdated: Response error: RPC error -32603 - Internal error: getting receipt: Tx receipt not found: get receipt for 1�-g�j*�J.�xQD��A�P@���Q�|: leveldb: not found: Tx receipt not found
```
and 
```
{ code: -32603,
  message: 'Internal error',
  data:
   'get receipt: Tx receipt not found: get receipt for ��-,�)u\t J&զ/��\u0004�}�!�\u0017�\'�F�Bnl]: leveldb: not found: Tx receipt not found' }
```
So when receipt is not found, query server should return nil receipt not error. We need to fix this problem in `GetBlockLogs` and `EvmTxReceipt` functions.

Note: currently, we don't store failed txs receipts in db so we probably need to review this issue once https://github.com/loomnetwork/loomchain/issues/1242 has been resolved.

**Comment by enlight** [comment]
Which cluster is this happening on?

**Comment by pathornteng** [comment]
Asia1

**Comment by enlight** [comment]
Hacked around this in https://github.com/loomnetwork/loomchain/pull/1397
