### ISSUE TITLE
Improve EVM e2e test

### ISSUE THREAD

**Issue by pathornteng** [loomnetwork/loomchain#1398]
Currently, our e2e tests on EVM are quite weak and it does not cover all endpoint. Moreover, our EVM code is quite spaghetti, rendering it really difficult to change. We need to expand our test in order to reduce the number of bugs and improve our code quality. We should improve the tests at least as follow.
1. Make sure that e2e test cover all the /eth endpoint
2. Test query EVM transaction receipts both failed txs and success txs
3. Test deploy and call more complex solidity contract
4. Make expected output more precise (possibly we can do after stricter output matching https://github.com/loomnetwork/loomchain/issues/1367)

**Comment by Sriep** [comment]
The truffle tests `https://github.com/loomnetwork/loomchain/tree/master/e2e/tests` tested most of the /eth endpoints. They could probably be reactivated and extended.

**Comment by pathornteng** [comment]
Great, can we reactivate it? any reason why it was deactivated in the first place?

**Comment by Sriep** [comment]
Truffle tests being reactivated in https://github.com/loomnetwork/loomchain/pull/1419

**Comment by pathornteng** [comment]
Truffle tests have been reactivated and more tests have been added.
