### ISSUE TITLE
Enabling the downtime slashing feature on PlasmaChain could slash everyone

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1402]
`MaxDowntimePercentage` is zero on PlasmaChain, and it can't be changed by the `dpos3 set-max-downtime-percentage` command until `dpos:v3.4` is enabled. Problem is if we enable `dpos:v3.4` and an election happens before we have time to set `MaxDowntimePercentage` to something other than zero EVERYONE will get slashed because every validator misses at least some blocks every period.

It seems we can work around this by setting the downtime slashing percentage to zero using `dpos3 set-slashing-percentages` command before enabling `dpos:v3.4`, then setting the `MaxDowntimePercentage` to a reasonable value, and then changing the downtime slashing percentage back to the desired value.

However, it'd be better if we just fix this feature to skip downtime slashing if `MaxDowntimePercentage` is zero.

**Comment by pathornteng** [comment]
`MaxDowntimePercentage` has a default value which is 50%. https://github.com/loomnetwork/loomchain/blob/445a4053cf53ac1582c7cb5dd5dbd688b2a048a0/builtin/plugins/dposv3/dpos.go#L1449

**Comment by enlight** [comment]
Ah, good point, 50% should be safe enough.
