### ISSUE TITLE
Implement eth_getStorageAt on /eth endpoint

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1444]
We need to implement [`eth_getStorageAt`](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getstorageat) on the `/eth` endpoint to support upgradable OpenZepplin contracts as requested in https://github.com/loomnetwork/loom-js/issues/306

**Comment by pathornteng** [comment]
Probably a good reference: https://github.com/ethereum/go-ethereum/blob/54b271a86dd748f3b0bcebeaf678dc34e0d6177a/internal/ethapi/api.go#L727

**Comment by pathornteng** [comment]
@eduardonunesp that's really useful articles. Thanks a lot.
