### ISSUE TITLE
Make IAVLFlushInterval configurable via on-chain config

### ISSUE THREAD

**Issue by pathornteng** [loomnetwork/loomchain#1451]
Currently, `IAVLFlushInterval` can only be configured via loom.yaml. We want it to be configured via on-chain config as well. Loom binary should look for the config value from loom.yaml first and then on-chain config and finally default config in this sequence.  We should add `IAVLFlushInterval` to on-chain config protobuf under `AppStoreConfig`.

**Comment by enlight** [comment]
Resolved by https://github.com/loomnetwork/loomchain/pull/1453
