### ISSUE TITLE
Fix eth_getLogs does not return correct event logs 

### ISSUE THREAD

**Issue by pathornteng** [loomnetwork/loomchain#1455]
Currently `eth_getLogs` does not return events log for EVM contract called by another EVM contract. The event logs are in the transaction receipts but `eth_getLogs` somehow does not find it.  

```
pragma solidity >=0.4.18;

contract InnerEmitter {
    event MyEvent(uint indexed number);

    function sendEvent(uint i) public   {
        emit MyEvent(i);
    }
}

contract OuterEmitter {
    function sendEvent(uint i) public {
        InnerEmitter testInnerEmitter = new InnerEmitter();
        testInnerEmitter.sendEvent(i);
    }
}
```
Get event logs using curl, the address is the address of OuterEmitter contract
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"address":"0x6Ed911d2BD423Fdc48a0E7d368E5E04554ECE935"}],"id":83}' http://localhost:46658/eth
```

**Comment by pathornteng** [comment]
@Sriep comment on Slack
There are two reasons why getPastLogs might fail to retrieve logs that it should be able to:
1) The incorrect logs are stored.
2) The correct logs are stored in the database, but eth_getLogs is failing to retrieve them.
You seem to be suggesting that 2) is the problem.
So how about doing an eth_getTransactionReceipt to show the correct logs are present. Then do an eth_getLogs to show eth_getLogs failing.

**Comment by Sriep** [comment]
`Get event logs using curl, the address is the address of OuterEmitter contract` The address of the `OuterEmitter` should not appear in the logs. Only the address of the Solidity contract that emitted the event should appear.
So we have two cases.
GoContract -calls-> InnerEmitter-->emits event
GoContract -calls-> OuterEmitter -calls-> InnerEmitter --> emits event.
In both cases, ists the `InnerEmitter` that emits the event. So it is the inner emitter that appears in the logs.
What is confusing, I think, is that its a different InnerEmitter in each case. When the OuterEmitter was deployed the Solidity code imported the InnerEmitter, but does not know anything about a pre-existing InnerEmitter so creates its own. So there are two `InnerEmitter`s with two different address and that is what appears in the logs.
   ```
piers innerEmitter.address 0x60ab575af210cc952999976854E938447E919871
piers outerEmitter.address 0xB681FBf4b36c49e0811Ee640CcA1933aB57Be81e
piers go contract receipt { transactionHash: '0x4a04bea653120c2758cef8a68429024df21c1eaad13d8c6aec28de38cd559b3c',
  transactionIndex: 0,
  blockHash: '0xca9c4cd59d34a2c8eee6982a2faf44364c135b68c54a8c05779f616f547a3995',
  blockNumber: 28,
  from: '0xb9fa0896573a89cf4065c43563c069b3b3c15c37',
  cumulativeGasUsed: 0,
  gasUsed: 0,
  contractAddress: '0x60ab575af210cc952999976854E938447E919871',
  to: null,
  logs: 
   [ { logIndex: 0,
       transactionIndex: 0,
       transactionHash: '0x4a04bea653120c2758cef8a68429024df21c1eaad13d8c6aec28de38cd559b3c',
       blockHash: '0xca9c4cd59d34a2c8eee6982a2faf44364c135b68c54a8c05779f616f547a3995',
       blockNumber: 28,
       address: '0x60ab575af210cc952999976854E938447E919871',
       data: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
       topics: [Array],
       id: 'log_4582a0cb' },
     { logIndex: 1,
       transactionIndex: 0,
       transactionHash: '0x4a04bea653120c2758cef8a68429024df21c1eaad13d8c6aec28de38cd559b3c',
       blockHash: '0xca9c4cd59d34a2c8eee6982a2faf44364c135b68c54a8c05779f616f547a3995',
       blockNumber: 28,
       address: '0xfF3Ee22fE3B0cD7C8Ff5b27b819b9f63457eef4f',
       data: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
       topics: [Array],
       id: 'log_3b3efd60' } ],
  logsBloom: '0x0190c083c080a80205',
  status: true }
  ```
```
let innerEmitter = await InnerEmitter.deployed();
let outerEmitter = await OuterEmitter.deployed();
console.log("piers innerEmitter.address",innerEmitter.address)
console.log("piers outerEmitter.address",outerEmitter.address)

const innerEmitterValue = 31;
const outerEmitterValue = 63;

const sampleGoContract = await Contracts.SampleGoContract.createAsync(
    client,
    new Address(client.chainId, LocalAddress.fromPublicKey(publicKey))
);

await sampleGoContract.testNestedEvmCallsAsync(
    new Address(client.chainId, LocalAddress.fromHexString(innerEmitter.address)),
    new Address(client.chainId, LocalAddress.fromHexString(outerEmitter.address)),
    innerEmitterValue,
    outerEmitterValue,
);
const goContractLogs = await web3js.eth.getPastLogs({
    address: innerEmitter.address,
});

const receipt = await web3js.eth.getTransactionReceipt(goContractLogs[0].transactionHash);
const logsFromGoContract = receipt.logs;
console.log("piers go contract receipt", receipt)

assert.equal(2, logsFromGoContract.length, "number of logs from go contract");
assert.equal(logsFromGoContract[0].topics[1], web3.utils.padLeft(innerEmitterValue, 64), "check inner emitter value");
assert.equal(logsFromGoContract[1].topics[1], web3.utils.padLeft(outerEmitterValue, 64), "check outer emitter value");
console.log("piers logsFromGoContract", logsFromGoContract)

const innerEmitterResult = await innerEmitter.sendEvent(innerEmitterValue);
const innerEmitterReceipt = await web3js.eth.getTransactionReceipt(innerEmitterResult.receipt.transactionHash);
const logsFromInnerEmitter = innerEmitterReceipt.logs;
console.log("piers logsFromInnerEmitter", logsFromInnerEmitter)
```

**Comment by pathornteng** [comment]
Ok I have tested with Ganache and here is the expected behavior 
1. The address on logs should be the address of the contract that emits the events. I tested, the logs on the receipts have correct address.
2. I tried querying with InnerEmitter address. Logs show up with InnerEmitter address. This is also correct.
3. The tx results returned from sending tx shows logs with OutterEmitter address. This is not correct. The logs should have InnerEmitter address but somehow it gets OutterEmitter address. However, we have to fix this in loom-js. One this line, we put contract address on logs instead of using address from event https://github.com/loomnetwork/loom-js/blob/a589855a65d1aa2f25c7657f2467ea1a5f11aeed/src/loom-provider.ts#L858

**Comment by enlight** [comment]
>However, we have to fix this in loom-js. One this line, we put contract address on logs instead of using address from event https://github.com/loomnetwork/loom-js/blob/a589855a65d1aa2f25c7657f2467ea1a5f11aeed/src/loom-provider.ts#L858

This is the old `/query` endpoint code path, it'll be deprecated soon, the important thing is that the `/eth` endpoint returns the correct data.

**Comment by pathornteng** [comment]
The data returned from `/eth` is correct. I think we can close this issue.
