### ISSUE TITLE
Fix Go contract emits events on failed txs

### ISSUE THREAD

**Issue by pathornteng** [loomnetwork/loomchain#1465]
Currently, if a tx passes in `CheckTx` but fails in `DeliverTx`, all the emitted events before the tx fails will still be saved to `event.db`. We need to clear out emitted events if the tx fails in `DeliverTx`. This problem seems to be tricky since we don't generate tx hash for Go tx like EVM tx.

**Comment by enlight** [comment]
Should be resolved by https://github.com/loomnetwork/loomchain/pull/1467
