### ISSUE TITLE
Make a node panic if it detects an active feature flag not supported by the current build

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1494]
Currently the ChainConfigManager will cause a node to panic if it attempts to activate a feature that's not supported by the current build, however, if a node is restored from a jump-start on an old build the node will run until it hits an app hash mismatch... at which point it has to be restored from the jump-start again.

**Comment by enlight** [comment]
Should probably do the same for on-chain config changes.

**Comment by atchapcyp** [comment]
> Should probably do the same for on-chain config changes.

Currently, we don't have the build number collected in the on-chain config store.
It is impossible to check the build number of the config that already applied.
Need your suggestion.

**Comment by enlight** [comment]
Suggested an approach in the PR

**Comment by enlight** [comment]
Resolved by https://github.com/loomnetwork/loomchain/pull/1507
