### ISSUE TITLE
Move the NonceTxHandler from a package level varable

### ISSUE THREAD

**Issue by Sriep** [loomnetwork/loomchain#1508]
Currently, the [NonceTxHandler is a file variable](https://github.com/loomnetwork/loomchain/blob/master/auth/auth.go#L189), this is a problem when replay transactions on different threads. We need to redo this so that the NonceTxHandler is attached to the TxHandler.

**Comment by enlight** [comment]
Resolved by https://github.com/loomnetwork/loomchain/pull/1510
