### ISSUE TITLE
EthFilter not support arrays of addresses filter

### ISSUE THREAD

**Issue by phoorichet** [loomnetwork/loomchain#1531]
### Issue 

https://github.com/loomnetwork/loomchain/blob/025ca1ff6ac226127f8b0da937478d8e24fd118e/rpc/eth/jsonrpc_conversion.go#L282-L292

[`EthFilter`](https://github.com/loomnetwork/loomchain/blob/025ca1ff6ac226127f8b0da937478d8e24fd118e/rpc/eth/jsonrpc_conversion.go#L282) contains the `Addresses` field which is an array of addresses. However, when the function `UnmarshalEthFilter` get called, the filter struct contain address, which is a string. 

https://github.com/loomnetwork/loomchain/blob/337b5b95bc34b995bb485b6918fefa49bf4178f8/eth/utils/utils.go#L24

Once the client calls `getevmlogs` with addresses filter, it ignores the addresses field and unmarshals only `address` field. Thus, the client with addresses filter is not working as expected.

https://github.com/loomnetwork/loomchain/blob/337b5b95bc34b995bb485b6918fefa49bf4178f8/eth/utils/utils.go#L35

### Expected 

`UnmarshalEthFilter` function should unmarshal the request with `addresses` fields.

**Comment by pathornteng** [comment]
This is an old endpoint and will soon be deprecated. Close this issue.
