### ISSUE TITLE
Investigate disabling preimage recording in EVM

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1576]
Currently when we create the EVM in loomchain with set `EnablePreimageRecording: true`, we should investigate whether this is of any use to us, if not - can we safely disabled this without causing a consensus failure, or do we need a to add an on-chain config setting to toggle this off?

**Comment by pathornteng** [comment]
`Preimage` cache stores `sha3(key)` -> `data` of EVM state. `Preimage` is intended to be used for debugging pre-commit state. So we can safely set  `EnablePreimageRecording: false`. I don't see any reason why we need to enable this in the future. No need for setting to toggle this config.

**Comment by enlight** [comment]
Resolved by https://github.com/loomnetwork/loomchain/pull/1579
