### ISSUE TITLE
eth_getTransactionByBlockNumberAndIndex returns wrong transaction

### ISSUE THREAD

**Issue by abalev** [loomnetwork/loomchain#1595]
On local node eth_getTransactionByBlockNumberAndIndex for one specific Bloc (13586313) returns transaction 29D36D651D2D1297D12D3021D903DC38E434CEA37EB164F9E1491F2B089CF787 but from https://plasma-alpha.dappchains.com/eth it returns 0xbad440cf6b73b7a6290fb4ceabd47cc2bd7d7384b68c5ba79f63583e1ad4b2c2 (that seems to be the right transaction)
Tested with full jump-start from 2019-11-24 and 2019-11-3 (new installation each time)

Way to reproduce:

wget https://downloads.loomx.io/loom/linux/extdev-stable/loom

chmod +x loom

tar xfvz 2019-11-24-1919-loom-plasma-jump-start.tar.gz

mkdir blank

cd blank

cp ../loom-jump-start/loom.yml .

../loom init

cp chaindata/config/{priv_validator.json,node_key.json} ../loom-jump-start/chaindata/config/

cd ../loom-jump-start

../loom run --persistent-peers tcp://1cba97a0a108cb0de51e5a3ff6ac15d70e0fa076@52.53.145.158:46656,tcp://367a9fa0df0afeed204c3360867e37ef03da5b97@52.53.184.91:46656,tcp://7b537b6ad25b5b13864ec20bed8803489189a274@54.193.119.132:46656,tcp://d7623e990790048db76c5d6a25e12efa818aaef1@52.53.221.33:46656 

curl --location --request POST "http://localhost:46658/eth" \
  --header "Content-Type: application/json" \
  --data  '{"jsonrpc":"2.0",
  "method":"eth_getTransactionByBlockNumberAndIndex",
  "params":["0xcf4f89", "0x0"],
  "id":1}'

Returns :
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "loom error: failed to find result of tx 29D36D651D2D1297D12D3021D903DC38E434CEA37EB164F9E1491F2B089CF787: Tx (29D36D651D2D1297D12D3021D903DC38E434CEA37EB164F9E1491F2B089CF787) not found",
    "data": ""
  }
}

Expected :
{
  "result": {
    "hash": "0xbad440cf6b73b7a6290fb4ceabd47cc2bd7d7384b68c5ba79f63583e1ad4b2c2",
    "nonce": "0xa16f",
    "blockHash": "0x9456e7507805d5b3ac70da7365fdf94b976bbb9f67d3256b6ff4cb58f3d54da7",
    "blockNumber": "0xcf4f89",
    "transactionIndex": "0x0",
    "from": "0x12f8e06b5279a6f91c315b37ac63c81184376e1b",
    "to": "0x6ae2fa4c52320bf298fd251c5b92fb3cd7558423",
    "value": "0x0",
    "gasPrice": "0x0",
    "gas": "0x0",
    "input": "0xdee11cb0"
  },
  "jsonrpc": "2.0",
  "id": 1
}

**Comment by enlight** [comment]
Looks like there might be an issue with the node the jump starts are created from, we'll fix this ASAP (likely next week).

**Comment by enlight** [comment]
A new jump-start is now available, let us know if it resolves your issue.

**Comment by abalev** [comment]
Thanks, I will check it this week

**Comment by abalev** [comment]
the result is just as expected, thanks
Closing
