### ISSUE TITLE
Local development environment

### ISSUE THREAD

**Issue by marcelomorgado** [loomnetwork/loomchain#1628]
Hi there, it's not clear for me which is the best channel to send this question, so I'm writing here and at the `loom-js` repo too.
My question is this: This is my first Loom usage and I'm wondering if is possible to have all that I need to run tests in my local development environment. i.e. erc20 transfers between chains.
In other words, I'm developing a dApp and want to test tokens transfers between chains using `ganache` as the Ethereum network and the local `loom` node as DAppChain. Somethings are working properly but the ERC20 transfer isn't working because seems that I need to have Gateway Oracle running locally.
Could you help me to clarify that? I'm correct in my thoughts or am I missing something?

Thanks!

**Comment by enlight** [comment]
Answered in loom-js repo.
