### ISSUE TITLE
secure-key- keys entered into state in inconstant order.

### ISSUE THREAD

**Issue by Sriep** [loomnetwork/loomchain#203]
The problem is that the `secure-key-` entries are entered into the state database by [iterating](https://github.com/ethereum/go-ethereum/blob/master/trie/database.go#L609) across a map of [preimages](https://github.com/ethereum/go-ethereum/blob/master/trie/database.go#L71), which means their order is undefined. 

This has been handled with a tempory fix, https://github.com/loomnetwork/loomchain/pull/191 which resorts the `secure-key-` entries after they are entred. A better solution would be to re-implement the go-ethereum [state.Database interface](https://godoc.org/github.com/ethereum/go-ethereum/core/state#Database).

By writing our own state. Database implementation we can use an array of preimages rather than a map.

**Comment by enlight** [comment]
EVM state has been moved to a separate DB, so the order in which `secure-key-` entries are written should no longer matter, though it might be worth looking into whether we can simplify & optimize the saving/loading of EVM state keys.
