### ISSUE TITLE
Ctrl+C stops Loom process, but not plugin processes

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [loomnetwork/loomchain#285]
If a plugin contract is deployed, pressing Ctrl+C in the console with a running Loom instance will stop Loom, but not the plugin process. This is annoying, since plugin process must be killed manually, otherwise, if Loom instance is started again, a new plugin process instance is spawned.

Expected behavior: plugin processes should go down with the Loom instance, since they seemingly serve no purpose by themselves.

**Comment by enlight** [comment]
We've moved away from using external plugins in production, so not going to spend any more time on this.
