### ISSUE TITLE
Pubsub changes from tendermint repository 

### ISSUE THREAD

**Issue by sidharth747** [loomnetwork/loomchain#793]
bucky [5:44 AM]
Hi guys. We just tagged `v0.31.0-dev0` and would appreciate some feedback. There’s one more major PR to go for v0.31 (https://github.com/tendermint/tendermint/pull/3269). The big change in this version is to the pubsub internals - we no longer block on publishing events. This means clients may miss events if they’re not fast enough to receive them. The goal was to address issues #951, #1880, and #2826 (see the milestone https://github.com/tendermint/tendermint/milestone/19). Would be super valuable if folks could test it out to see if it somehow breaks their work flows, and to see if #3269 will be acceptable (imposing limits on number of subscribers and number of subscriptions per subscriber).

We’re probably going to need to do a serious rethink of the RPC at some point, and would be valuable to gather feedback. Basically we need to better differentiate endpoints that can be exposed to the public from those that are more for development, debugging, or administrative control. I’ve opened https://github.com/tendermint/tendermint/issues/3367 to start tracking this and solicit feedback, so if you have thoughts, please include them there!

**Comment by enlight** [comment]
Probably too complicated to backport this stuff, will have to wait until the next Tendermint upgrade https://github.com/loomnetwork/loomchain/issues/1279
