### ISSUE TITLE
ChainConfig.ListFeatures should show features enabled via migrations

### ISSUE THREAD

**Issue by pathornteng** [loomnetwork/loomchain#952]
If `StoreState.SetFeature` is called in a migration (or anywhere else other than `ChainConfigManager`) to immediately enable a feature that feature won't be returned by `ChainConfig.ListFeatures`. Need to add `StoreState,EnabledFeatures`, and modify `ChainConfig.ListFeatures` to merge the feature list from `StoreState,EnabledFeatures` with the ones it already knows about.

**Comment by enlight** [comment]
Resolved by #1316
